// 🌊 this file is auto-generated by Fernando Rojo's script. don't edit it.
// https://fernandorojo.co
import * as React from 'react'
import Svg, { SvgProps, Path } from 'react-native-svg'
const Medication = (props: SvgProps) => (
  <Svg
    // width="20"
    // height="20"
    viewBox="0 0 24 24"
    stroke="black"
    fill="red"
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <Path
      d="M8.59998 16.4C7.72675 17.2049 6.57606 17.6409 5.3887 17.6168C4.20134 17.5926 3.06934 17.1102 2.22957 16.2704C1.38981 15.4306 0.907371 14.2986 0.883216 13.1113C0.859061 11.9239 1.29506 10.7732 2.09998 9.9L9.89998 2.1C10.7732 1.29508 11.9239 0.859084 13.1112 0.883239C14.2986 0.907394 15.4306 1.38983 16.2704 2.2296C17.1101 3.06936 17.5926 4.20137 17.6167 5.38873C17.6409 6.57609 17.2049 7.72678 16.4 8.6M5.99898 5.999L10.249 10.249"
      stroke="white"
      strokeWidth={1.5}
      strokeLinecap="round"
      strokeLinejoin="round"
    />
    <Path
      d="M17.25 15V19.5M15 17.25H19.5M23.25 15.75C23.2533 17.4965 22.6605 19.1918 21.5695 20.5556C20.4784 21.9194 18.9546 22.8699 17.25 23.25C15.5453 22.8699 14.0215 21.9194 12.9305 20.5556C11.8394 19.1918 11.2466 17.4965 11.25 15.75V13.5C11.25 13.1022 11.408 12.7206 11.6893 12.4393C11.9706 12.158 12.3521 12 12.75 12H21.75C22.1478 12 22.5293 12.158 22.8106 12.4393C23.0919 12.7206 23.25 13.1022 23.25 13.5V15.75Z"
      stroke="white"
      strokeWidth={1.5}
      strokeLinecap="round"
      strokeLinejoin="round"
    />
  </Svg>
)
export default Medication
